ci:
  autoupdate_schedule: quarterly
repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v10.0.3'
    hooks:
      - id: eslint
        additional_dependencies:
            - "eslint@v10.0.3"
            - "@eslint/js@v10.0.1"
            - "globals"
        files: \.js?$
        types: [file]
        args:
        - --fix

