ci:
  autoupdate_schedule: quarterly
repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v9.27.0'
    hooks:
      - id: eslint
        additional_dependencies:
            - "eslint@v9.27.0"
            - "@eslint/js@v9.27.0"
            - "globals"
        files: \.js?$
        types: [file]
        args:
        - --fix

